### ISSUE TITLE
"AttributeError: 'HTTPMessage' object has no attribute 'getheader'  " on token_login using python 3.4.3

### ISSUE THREAD

**Issue by sairoshan** [wialon/python-wialon#8]
I am trying to login using the following code using python 3.4.3:
```
from wialon.api import Wialon, WialonError
from wialon import flagsfrom wialon.api import Wialon, WialonError
from wialon import flags


wialon_api = Wialon()
result = wialon_api.token_login(token='XXXXX')
```

Getting below error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/EM3GIS/EM3GIS/gisenv/lib/python3.4/site-packages/wialon/api.py", line 176, in get
    return self.call(action_name, *args, **kwargs)
  File "/home/admin/EM3GIS/EM3GIS/gisenv/lib/python3.4/site-packages/wialon/api.py", line 127, in call
    return self.request(action, self.__base_api_url, all_params)
  File "/home/admin/EM3GIS/EM3GIS/gisenv/lib/python3.4/site-packages/wialon/api.py", line 141, in request
    content_type = response.info().getheader('Content-Type')
AttributeError: 'HTTPMessage' object has no attribute 'getheader'

**Comment by ashmigelski** [comment]
Thanks for reporting :+1:
We've fixed and updated packageplease check
